---
# Temporary playbook to add blocklists, whitelist, and blacklist
- name: Add Pi-hole Lists
  hosts: pihole
  become: true
  gather_facts: false
  
  tasks:
    - name: Add remaining blocklists
      shell: |
        curl -s -X POST 'http://localhost/api/lists?type=block' \
          -H 'Content-Type: application/json' \
          -d '{"address":"{{ item }}","comment":"Added via Ansible","enabled":true}'
      loop:
        - "https://someonewhocares.org/hosts/zero/hosts"
        - "https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/BaseFilter/sections/adservers.txt"
        - "https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext"
      register: blocklist_result
      failed_when: false
      changed_when: "'success' in blocklist_result.stdout"

    - name: Add whitelist domains
      shell: |
        curl -s -X POST 'http://localhost/api/lists?type=allow' \
          -H 'Content-Type: application/json' \
          -d '{"address":"{{ item }}","comment":"Whitelisted via Ansible","enabled":true}'
      loop:
        - "github.com"
        - "microsoft.com"
        - "apple.com"
        - "google.com"
      register: whitelist_result
      failed_when: false
      changed_when: "'success' in whitelist_result.stdout"

    - name: Add blacklist domain
      shell: |
        curl -s -X POST 'http://localhost/api/lists?type=block' \
          -H 'Content-Type: application/json' \
          -d '{"address":"{{ item }}","comment":"Blacklisted via Ansible","enabled":true}'
      loop:
        - "ads.example.com"
      register: blacklist_result
      failed_when: false
      changed_when: "'success' in blacklist_result.stdout"

    - name: Update gravity to process new lists
      command: pihole updateGravity
      register: gravity_result
      changed_when: true

    - name: Display results
      debug:
        msg: |
          Lists Added Successfully!
          - Blocklists: 3 additional lists added
          - Whitelist: 4 domains added
          - Blacklist: 1 domain added
          - Gravity updated: {{ 'Success' if gravity_result.rc == 0 else 'Failed' }}

# Made with Bob
