all:
  hosts:
    pihole_server:
      ansible_host: "{{ pihole.ssh_host }}"
      ansible_user: "{{ pihole.ssh_user }}"
      ansible_ssh_pass: "{{ pihole.ssh_password }}"
      ansible_become: yes
      ansible_become_password: "{{ pihole.ssh_password }}"
  children:
    pihole_servers:
      hosts:
        pihole:
          ansible_host: "{{ pihole.ssh_host }}"
          ansible_user: "{{ pihole.ssh_user }}"
          ansible_ssh_pass: "{{ pihole.ssh_password }}"
          ansible_become: yes
          ansible_become_method: sudo
          ansible_become_pass: "{{ pihole.ssh_password }}"
          
          # Pi-hole specific variables
          pihole_admin_password: "{{ pihole.admin_password }}"
          pihole_interface: "{{ pihole.interface }}"
          pihole_dns_servers: "{{ pihole.dns_servers }}"
          pihole_web_interface: "{{ pihole.web_interface | default(true) }}"
          pihole_web_port: "{{ pihole.web_port | default(80) }}"
          pihole_dhcp_enabled: "{{ pihole.dhcp.enabled | default(false) }}"
          pihole_dhcp_start: "{{ pihole.dhcp.start_ip | default('') }}"
          pihole_dhcp_end: "{{ pihole.dhcp.end_ip | default('') }}"
          pihole_dhcp_router: "{{ pihole.dhcp.router_ip | default('') }}"
          pihole_dhcp_lease_time: "{{ pihole.dhcp.lease_time | default('24h') }}"
          
          # Lists configuration
          pihole_blocklists: "{{ pihole.blocklists | default([]) }}"
          pihole_whitelist: "{{ pihole.whitelist | default([]) }}"
          pihole_delete_whitelist: "{{ pihole.delete_whitelist | default([]) }}"
          pihole_blacklist: "{{ pihole.blacklist | default([]) }}"
          pihole_delete_blacklist: "{{ pihole.delete_blacklist | default([]) }}"
          pihole_regex_blacklist: "{{ pihole.regex_blacklist | default([]) }}"
          pihole_delete_regex_blacklist: "{{ pihole.delete_regex_blacklist | default([]) }}"
          pihole_regex_whitelist: "{{ pihole.regex_whitelist | default([]) }}"
          pihole_delete_regex_whitelist: "{{ pihole.delete_regex_whitelist | default([]) }}"
          pihole_custom_dns: "{{ pihole.custom_dns | default([]) }}"
          
          # Network configuration
          pihole_network_postfix: "{{ pihole.network.postfix | default('local') }}"

    # Future expansion - additional machine groups
    # nas_servers:
    #   hosts:
    #     nas:
    #       ansible_host: "{{ machines.nas.ssh_host }}"
    #       ansible_user: "{{ machines.nas.ssh_user }}"
    #       ansible_ssh_pass: "{{ machines.nas.ssh_password }}"
    
    # media_servers:
    #   hosts:
    #     plex:
    #       ansible_host: "{{ machines.plex.ssh_host }}"
    #       ansible_user: "{{ machines.plex.ssh_user }}"
    #       ansible_ssh_pass: "{{ machines.plex.ssh_password }}"

  vars:
    # Global Ansible settings
    ansible_become: true
    ansible_become_method: "{{ ansible.become_method | default('sudo') }}"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_timeout: "{{ ansible.timeout | default(300) }}"